# based on https://www.digitalocean.com/community/tutorials/how-to-install-apache-kafka-on-ubuntu-20-04

---
- hosts: prod
  become: yes
  gather_facts: no

  vars:
    kafka_dir: /opt/kafka_2.13-3.5.0
    kafka_link: "https://dlcdn.apache.org/kafka/3.5.0/kafka_2.13-3.5.0.tgz"

  tasks:
    - name: Update apt cache and install java
      apt: name=default-jre-headless state=latest update_cache=yes

    - name: Add kafka group
      group: name=kafka state=present

    - name: Add kafka user
      user: name=kafka group=kafka state=present

    - name: Download and unzip
      unarchive:
        remote_src: yes
        src: "{{kafka_link}}"
        dest: "/opt"
        mode: 0755
        owner: kafka
        group: kafka

    - name: Create services
      template:
        src: "files/{{item}}.service.j2"
        dest: "/etc/systemd/system/{{item}}.service"
      notify: "Restart {{item}}"
      loop: [zookeeper, kafka]

    - name: Enable services
      systemd: name='{{item}}' enabled=yes
      loop: [zookeeper, kafka]


  handlers:
    - name: Restart zookeeper
      systemd: name=zookeeper state=restarted
      notify: Check zookeeper

    - name: Restart kafka
      systemd: name=kafka state=restarted
      notify: Check kafka

    - name: Check zookeeper
      wait_for:
        host: localhost
        port: 2181
        delay: 5
        msg: Zookeeper is not responding

    - name: Check kafka
      wait_for:
        host: localhost
        port: 9092
        delay: 5
        msg: Kafka is not responding


