- name: Install java
  apt: name=default-jre-headless state=present

- name: Add kafka group
  group: name=kafka state=present

- name: Add kafka user
  user: name=kafka group=kafka state=present

- name: Download and unzip
  unarchive:
    remote_src: yes
    src: "{{kafka_link}}"
    dest: "/opt"
    mode: 0755
    owner: kafka
    group: kafka

- name: Create services
  template:
    src: "{{item}}.service.j2"
    dest: "/etc/systemd/system/{{item}}.service"
  notify: "Restart {{item}}"
  loop: [zookeeper, kafka]

- name: Enable services
  systemd: name="{{item}}" enabled=yes
  loop: [zookeeper, kafka]
