- name: Restart zookeeper
  systemd: name=zookeeper state=restarted
  notify: Check zookeeper

- name: Restart kafka
  systemd: name=kafka state=restarted
  notify: Check kafka

- name: Check zookeeper
  wait_for:
    host: localhost
    port: 2181
    delay: 5
    msg: Zookeeper is not responding

- name: Check kafka
  wait_for:
    host: localhost
    port: 9092
    delay: 5
    msg: Kafka is not responding
